name: ExplainingImageClassifiers
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pip=19.2.3
  - pandas=1.0.0
  - matplotlib=3.1.3
  - jupyter=1.0.0
  - tensorflow=1.14.0
  - Pillow=6.1.0
  - scikit-image=0.15.0
  - eli5=0.10.1
  - lime=0.1.1.30
  - shap=0.34.0
  - pip:
    - image-classifiers==0.2.2