name: NumpyCNN
channels:
  - conda-forge
dependencies:
  - python=3.7.3
  - pip=19.2.3
  - pytest=5.0.1
  - pandas=1.0.0
  - matplotlib=3.1.3
  - jupyter=1.0.0
  - seaborn=0.10.0
  - scikit-learn=0.22.1
  - pip:
      - tensorflow==2.0.0
